### ISSUE TITLE
Multi-GPUs:  CUDA error: initialization error

### ISSUE THREAD

**Issue by Tokkiu** [meta-pytorch/torchrec#197]
Hi, thanks for your awesome work! The lib is amazing and I am really into this project.
However, I met some problem when I want to run the example training DLRM model.
Basically I prepared the conda env as readme and it goes well.
```
conda create -n torchrec python=3.8
conda activate torchrec
conda install pytorch cudatoolkit=11.3 -c pytorch-nightly
pip install torchrec-nightly
git clone https://github.com/pytorch/torchrec.git
cd torchrec/examples/dlrm
```
Then I use command lines provided by yours to run DLRM.
```
torchx run -s local_cwd dist.ddp -j 1x2 --script dlrm_main.py
```
Then errors occurred as follows:
```
dlrm_main/0 [1]:frame #58: <unknown function> + 0x17cd15 (0x55ad313f2d15 in /home/jingqi/anaconda3/envs/rec/bin/python)
dlrm_main/0 [1]:frame #59: _PyEval_EvalFrameDefault + 0x4c0 (0x55ad3144ce60 in /home/jingqi/anaconda3/envs/rec/bin/python)
dlrm_main/0 [1]:frame #60: _PyEval_EvalCodeWithName + 0x260 (0x55ad31442600 in /home/jingqi/anaconda3/envs/rec/bin/python)
dlrm_main/0 [0]:
dlrm_main/0 [0]:Evaluating test set: 0it [00:00, ?it/s][1]:frame #61: _PyFunction_Vectorcall + 0x534 (0x55ad31443b64 in /home/jingqi/anaconda3/envs/rec/bin/python)
dlrm_main/0 [1]:frame #62: <unknown function> + 0x166b2e (0x55ad313dcb2e in /home/jingqi/anaconda3/envs/rec/bin/python)
dlrm_main/0 [1]:frame #63: _PyEval_EvalFrameDefault + 0x4f83 (0x55ad31451923 in /home/jingqi/anaconda3/envs/rec/bin/python)
dlrm_main/0 [1]:
dlrm_main/0 [1]:terminate called after throwing an instance of 'c10::CUDAError'
dlrm_main/0 [1]:  what():  CUDA error: initialization error
dlrm_main/0 [1]:CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
dlrm_main/0 [1]:For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
dlrm_main/0 [1]:Exception raised from insert_events at /opt/conda/conda-bld/pytorch_1649229055957/work/c10/cuda/CUDACachingAllocator.cpp:1420 (most recent call first):
dlrm_main/0 [1]:frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x4d (0x7f7c9179734d in /home/jingqi/anaconda3/envs/rec/lib/python3.8/site-packages/torch/lib/libc10.so)
dlrm_main/0 [1]:frame #1: <unknown function> + 0x1e50b (0x7f7cbef7b50b in /home/jingqi/anaconda3/envs/rec/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
dlrm_main/0 [1]:frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x23a (0x7f7cbef8049a in /home/jingqi/anaconda3/envs/rec/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
dlrm_main/0 [1]:frame #3: <unknown function> + 0x2f82e8 (0x7f7ccffa62e8 in /home/jingqi/anaconda3/envs/rec/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
dlrm_main/0 [1]:frame #4: c10::TensorImpl::release_resources() + 0x175 (0x7f7c9177da15 in /home/jingqi/anaconda3/envs/rec/lib/python3.8/site-packages/torch/lib/libc10.so)
dlrm_main/0 [1]:frame #5: <unknown function> + 0x1e53e9 (0x7f7ccfe933e9 in /home/jingqi/anaconda3/envs/rec/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
dlrm_main/0 [1]:frame #6: <unknown function> + 0x4d6e7c (0x7f7cd0184e7c in /home/jingqi/anaconda3/envs/rec/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
```
![Screenshot 2022-04-07 at 12 21 55 AM](https://user-images.githubusercontent.com/13414571/162021612-48aa5b75-0f98-479a-a240-35ffccfd1050.png)

My env is 4 gpus with each has 23GB GPU memory and the server memory is 256G.
I tried to decrease the batch size but it still went wrong so I guess the error is not from memory space limit.

Do you have any ideas or suggestions for better use?

**Comment by joshuadeng** [comment]
Hi @Tokkiu, thanks for pointing out this error! 
There is currently an issue with using dataloader workers that causes this CUDA error. 
To mitigate it you can run:
`torchx run -s local_cwd dist.ddp -j 1x2 --script dlrm_main.py -- --num_workers 0`

I'm putting out a fix to set the num_workers arg to 0 by default in the meantime.

**Comment by Tokkiu** [comment]
Thanks for your quick reply. I solved the issued as your instruction. I will close this issue. Also, if I can help to contribute this repo, pls let me know.

> Hi @Tokkiu, thanks for pointing out this error! There is currently an issue with using dataloader workers that causes this CUDA error. To mitigate it you can run: `torchx run -s local_cwd dist.ddp -j 1x2 --script dlrm_main.py -- --num_workers 0`
> 
> I'm putting out a fix to set the num_workers arg to 0 by default in the meantime.

**Comment by joshuadeng** [comment]
Definitely, feel free to contribute!
